[plugins]
korge = { id = "com.soywiz.korge", version = "5.3.0" }
[libraries]
play-services = { group = "com.google.android.gms", name = "play-services", version.ref = "play-services" }
[versions]
play-services = "12.0.1"
#korge = { id = "com.soywiz.korge", version = "999.0.0.999" }
